# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t reverseproxy ./udagram-reverseproxy
# Do similar for other three images
# Tagging
- docker tag udagram-api-feed pavan2106/udagram-api-feed:v7
- docker tag udagram-api-user pavan2106/udagram-api-user:v7
- docker tag udagram-frontend pavan2106/udagram-frontend:v7
- docker tag reverseproxy pavan2106/reverseproxy:v7
# Do similar for other three images
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push pavan2106/udagram-api-feed:v7
- docker push pavan2106/udagram-api-user:v7
- docker push pavan2106/udagram-frontend:v7
- docker push pavan2106/reverseproxy:v7
# Do similar for other three images